services:
  user-db:
    image: postgres:16
    environment:
      POSTGRES_USER: aditya
      POSTGRES_PASSWORD: aditya
      POSTGRES_DB: user
    # ports:
    #   - 5432:5432
    volumes:
      - ./docker-data/user-db:/var/lib/postgresql/data
    restart: always
  order-db:
    image: postgres:16
    environment:
      POSTGRES_USER: aditya
      POSTGRES_PASSWORD: aditya
      POSTGRES_DB: order
    # ports:
    #   - 5433:5432
    volumes:
      - ./docker-data/order-db:/var/lib/postgresql/data
    restart: always
  user-service:
    build: ./services/user
    ports:
      - 8000:8000
    depends_on:
      - user-db
    env_file:
      - ./services/user/.env.docker
    restart: always
  order-service:
    build: ./services/order
    ports:
      - 8001:8001
    depends_on:
      - order-db
    env_file:
      - ./services/order/.env.docker
    restart: always
  bff-service:
    build: ./services/bff
    ports:
      - 3007:3000
    depends_on:
      - user-service
      - order-service
    env_file:
      - ./services/bff/.env.docker
    restart: always